vizia/vizia

examples/binding_test.rs, examples/counter.rs, examples/list.rs, examples/resizable_table.rs, examples/todo.rs, src/application.rs, src/binding/mod.rs, src/views/list.rs
Changes binding to no longer act as a parent view. Binding views are now invisible siblings to their content.
=> Binding changes

glutin/src/application.rs
I ran into some missing features while building a view with mouse interactivity. These fix everything on my end.
Please let me know if you want me to write tests!
=> glutin: handle mouse scroll, set mouse state

core/src/views/for_each.rs
Less restrictive than a Fn. Enables some code I would like to write.
=> Make ForEach take a FnMut

baseview/Cargo.toml
This fixes a pretty nasty crash when adding and removing VSTs built with vizia_baseview
=> Update to newest revision of raw-gl-context

core/src/default_theme.css, core/src/views/dropdown.rs, examples/controls/dropdown.rs
- Removes some unnecessary style attributes
- Moves the dropdown icon text into a pub const so people can import it
=> Small tweaks to improve dropdown QoL

baseview/src/application.rs, core/src/context.rs, glutin/src/application.rs
=> Refactor common code from application.rs into context.rs

core/src/handle.rs, core/src/style/mod.rs, core/src/style/selector.rs, core/src/style_system.rs, examples/test.rs
=> Add id matching selectors

core/src/context.rs
=> Propagate direct events directly

core/src/cache.rs
This adds some helper methods to get the absolute position of common points on a `BoundingBox` to make composing views easier
=> Added helper methods to `BoundingBox`

derive/src/lens.rs
And structs containing types that also aren't `pub`. Without this Rust will error out because you're trying to expose a hidden type from a `pub` struct in a `pub` module. Applying the same visibility to the module technically isn't necessary, but it makes the generated docs look neater because otherwise you'd end up with empty modules.
=> Fix the Lens derive macro for non-pub structs

baseview/Cargo.toml, core/Cargo.toml, core/src/cache.rs, core/src/context.rs, core/src/default_theme.css, core/src/handle.rs, core/src/layout/node.rs, core/src/state/lens.rs, core/src/storage/sparse_set.rs, core/src/storage/style_set.rs, core/src/style/mod.rs, core/src/style/parser.rs, core/src/style/property.rs, core/src/style_system.rs, core/src/text/layout.rs, core/src/text/mod.rs, core/src/view.rs, core/src/views/textbox.rs, examples/controls/textbox.rs, examples/test.rs, winit/Cargo.toml
=> Add multiline textboxes

core/src/views/label.rs
=> Update label doc string

baseview/src/application.rs, baseview/src/lib.rs, core/src/context.rs, core/src/context/draw.rs, core/src/context/mod.rs, core/src/context/proxy.rs, core/src/events/event_handler.rs, core/src/layout/node.rs, core/src/localization/mod.rs, core/src/modifiers/actions.rs, core/src/state/lens.rs, core/src/style/mod.rs, core/src/style/transform.rs, core/src/style_system.rs, core/src/text/layout.rs, core/src/view.rs, core/src/views/dropdown.rs, core/src/views/knob.rs, core/src/views/menu.rs, core/src/views/scrollview.rs, core/src/views/textbox.rs, examples/7GUIs/flight_booker.rs, examples/test.rs, src/lib.rs, winit/src/application.rs, winit/src/window.rs
Apply DPI scaling in vizia rather than relying on femtovg
=> Fix DPI scaling

core/src/localization/mod.rs
- Lets you specify constant values as fluent args
- Makes all keys passed as String instead of &'static str. maybe a Cow would be more appropriate? idk
- Re-exports FluentValue so users don't have to depend on fluent-bundle to make types compatible with us
=> Make localization more expressive

core/src/modifiers/actions.rs, core/src/views/dropdown.rs, core/src/views/label.rs
I updated the `dropdown` doc string with the example from the [book](https://github.com/vizia/vizia-book/blob/develop/src/views/dropdown.md).
=> Update `dropdown` doc string

core/src/views/element.rs
I updated the `Element` doc string with some examples I could come up with. I also saw that you are able to bind an `Element` to some data, but I'm not quite sure how exactly that works.
=> Update `Element` doc string

baseview/Cargo.toml, baseview/src/application.rs, baseview/src/lib.rs, baseview/src/proxy.rs, baseview/src/window.rs
This enables arborio to work* with baseview.
*there seems to be some bug with how scroll events are handled in baseview - I'm not seeing any horizontal scrolling.
=> Add event proxy for baseview

baseview/src/application.rs, core/src/context/mod.rs, core/src/handle.rs, core/src/layout/node.rs, core/src/lib.rs, core/src/storage/animatable_set.rs, core/src/storage/style_set.rs, core/src/views/scrollview.rs, core/src/views/textbox.rs, examples/views/textbox.rs, examples/window_modifiers.rs
- Expose `Key`
- Add `set_hover` method to context
- Add bool to textbox `on_submit` to distinguish between enter and defocus
- Scale border by scale factor for layout
=> Fix assorted issues

Cargo.toml, baseview/src/application.rs, baseview/src/window.rs, core/src/context/mod.rs, core/src/environment.rs, core/src/lib.rs, examples/ignore_default_theme.rs, winit/src/application.rs
Fixes a regression from the `Environment` changes in #159
=> Refactor code for ignoring default theme

core/resources/themes/default_theme.css, core/src/fonts.rs, core/src/views/checkbox.rs, core/src/views/radio_buttons.rs, examples/views/checkbox.rs, examples/views/radiobutton.rs
+ Add example for custom checkbox icon
=> Style and doc improvements for radio button

Cargo.toml, core/src/context/draw.rs, core/src/context/mod.rs, core/src/handle.rs, core/src/style/color.rs, core/src/style/mod.rs, core/src/style/parser.rs, core/src/style/property.rs, core/src/style_system.rs, core/src/view.rs, examples/style/outline.rs
Also changes 'green' color to match CSS when defined inline.
=> Add outline property

core/src/context/event.rs, core/src/context/mod.rs, core/src/events/event_manager.rs, core/src/state/lens.rs
- Add missing features to EventContext
- Remove unnecessary Clone bound from Map lens
- Added cx.add_global_listener()
Arborio now works on main :)
=> Multiple fixes

crates/vizia_core/resources/themes/default_theme.css, crates/vizia_core/src/views/knob.rs
Arrow key support for changing knob. Part of #55.
=> Add arrow key support for knob

crates/vizia_core/resources/themes/default_theme.css, crates/vizia_core/src/views/slider.rs
Arrow key support for changing sliders. Part of #55.
=> Add arrow key support for Slider

crates/vizia_core/src/events/event_manager.rs, crates/vizia_core/src/modifiers/actions.rs, crates/vizia_core/src/views/button.rs, crates/vizia_core/src/views/checkbox.rs, crates/vizia_core/src/views/label.rs, crates/vizia_core/src/views/menu.rs, crates/vizia_core/src/views/radio_buttons.rs, crates/vizia_core/src/views/slider.rs, crates/vizia_core/src/views/textbox.rs, crates/vizia_window/src/window_event.rs
=> Add Press and PressDown events

crates/vizia_core/src/context/event.rs, crates/vizia_core/src/context/mod.rs, crates/vizia_core/src/lib.rs, crates/vizia_core/src/modifiers/actions.rs
- impl AsMut<EventContext> for EventHandle
- Add EmitContext trait
=> Make EventHandle slightly nicer to use

crates/vizia_core/src/context/proxy.rs, crates/vizia_core/src/text/mod.rs, crates/vizia_core/src/text/movement.rs, crates/vizia_core/src/text/scrolling.rs, crates/vizia_core/src/views/scrollview.rs, crates/vizia_core/src/views/textbox.rs, crates/vizia_derive/src/ray.rs
- Scroll
- PageUp/PageDown
- Home/End
Closes #94
=> Textbox: new interactions

crates/vizia_core/src/systems/style.rs
=> Get element name from view method rather than style store

crates/vizia_core/src/context/event.rs, crates/vizia_core/src/context/mod.rs, crates/vizia_core/src/events/event_manager.rs, crates/vizia_window/src/window_event.rs, crates/vizia_winit/src/window.rs, examples/resources/test.css, examples/stylesheet.rs
=> Add window event to reload application stylesheets

crates/vizia_core/src/handle.rs, crates/vizia_core/src/input/entry.rs, crates/vizia_core/src/input/keymap.rs, crates/vizia_core/src/lib.rs, crates/vizia_core/src/localization/mod.rs, crates/vizia_core/src/state/binding.rs, crates/vizia_core/src/state/data.rs, crates/vizia_core/src/state/mod.rs, crates/vizia_core/src/state/res.rs, crates/vizia_core/src/state/store.rs, crates/vizia_core/src/text/selection.rs, crates/vizia_core/src/views/dropdown.rs, crates/vizia_core/src/views/list.rs, crates/vizia_core/src/views/mod.rs, crates/vizia_core/src/views/popup.rs, crates/vizia_core/src/views/scrollview.rs, crates/vizia_core/src/views/slider.rs, crates/vizia_core/src/views/table.rs, crates/vizia_core/src/views/textbox.rs, crates/vizia_derive/src/data.rs, crates/vizia_derive/src/lib.rs, examples/7GUIs/flight_booker.rs, examples/views/table.rs
This reverts commit 332c63c5c2c44c6549ebc111da9b48c171037586.
=> Revert "Replace `Data` trait with `Clone + PartialEq` (#269)"

crates/vizia_core/Cargo.toml, crates/vizia_core/resources/themes/default_layout.css, crates/vizia_core/src/context/draw.rs, crates/vizia_core/src/systems/layout.rs, crates/vizia_core/src/systems/text_constraints.rs, crates/vizia_core/src/text/cosmic.rs, crates/vizia_core/src/view.rs, crates/vizia_core/src/views/textbox.rs, examples/views/textbox.rs
=> Support RTL text in textboxes

crates/vizia_core/src/context/draw.rs, crates/vizia_core/src/view.rs
This is necessary if you want to have a custom draw method that uses the text draw stuff, lol
=> Add pub method to call sync_styles on current entity's text

crates/vizia_core/src/animation/cubic_curve.rs, crates/vizia_core/src/animation/mod.rs
Add Cubic Curve, inspired by algorithm in browser engines, to animation in vizia
=> Add CubicCurve to Animation

Cargo.toml, examples/7GUIs/timer.rs
Added Timer to 7GUI tasks examples.
I'll commit the fix after planned changes to the timer
=> Added Timer to 7GUI example

crates/vizia_core/src/binding/data.rs
Implement additional `Data` implementions (`Display`, `Vizibility`).
=> data implementations

crates/vizia_core/src/events/event.rs, crates/vizia_core/src/events/timer.rs, crates/vizia_winit/src/application.rs
this is a temporary fix until https://github.com/rust-windowing/winit/pull/3154 get merged in winit.
=> temporary fix for `MouseEnter` and `MouseLeave` window events on windows platform

crates/vizia_core/src/context/backend.rs, crates/vizia_winit/src/application.rs
fixed mouse enter and leave not using correct window size and updated `window_size` in `set_window_size`
=> fixed mouse enter and leave not using correct window size

crates/vizia_core/src/animation/animation_state.rs, crates/vizia_core/src/binding/binding_view.rs, crates/vizia_core/src/binding/store.rs, crates/vizia_core/src/context/backend.rs, crates/vizia_core/src/context/event.rs, crates/vizia_core/src/context/mod.rs, crates/vizia_core/src/context/resource.rs, crates/vizia_core/src/events/event_manager.rs, crates/vizia_core/src/modifiers/abilities.rs, crates/vizia_core/src/modifiers/actions.rs, crates/vizia_core/src/modifiers/style.rs, crates/vizia_core/src/resource.rs, crates/vizia_core/src/style/mod.rs, crates/vizia_core/src/systems/binding.rs, crates/vizia_core/src/systems/hover.rs, crates/vizia_core/src/systems/image.rs, crates/vizia_core/src/systems/style.rs, crates/vizia_core/src/view/handle.rs, crates/vizia_core/src/views/menu.rs
Restyle only the views that might need to be restyled.
=> Restyle speedup

crates/vizia_core/src/views/virtual_list.rs
I had the observation that `VirtualList` currently recreates the entire set of visible items when the scroll position changes. In practice, at least for my app, it's usually only one or two items that pass over the ends of the list on any particular frame of scrolling. So in theory I only need to rebuild those one or two items and not the whole thing (60+ rows in my case).
This PR is my attempt at implementing that idea. 
The general idea of the implementation goes something like this:
* The virtual list holds a `visible_items` list that contains the indices of the items in the backing list that are currently visible.
* For example, `[0,1,2,3]`, assuming you're at the initial scrollbar position with enough screen space for 4 items.
* We create an associated container for each slot, with …
=> RFC: Make VirtualList rebuild logic more "fine-grained".

crates/vizia_core/src/views/virtual_list.rs
This change allows `VirtualList` views to be generic over their backing storage type. Previously the backing storage was required to implement `Deref<Target = [T]>`, which prevented it from being used with alternative data structures like `VecDeque`, `IndexMap`, and so on. 
The bounds were unnecessarily restrictive since the only things that *really* mattered were that backing storage had a known `len` and could access an item by index. This change lets you specify both of these behaviors via closures and pass them into an alternate constructor `VirtualList::new_generic`. The original constructor `VirtualList::new` remains the same and simply delegates to the new method.
This is a small breaking API change in that the `item_content` method signature now expects a `MapRef<L, T>` rather …
=> Allow `VirtualList` to be generic over the backing storage.

.github/workflows/audit.yml, .github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/test.yml
Convenient for testing feature branches in forked repos before opening a pull request.
=> Enable manual dispatch of all GitHub workflows

crates/vizia_winit/src/window.rs
Handle `WindowEvent::SetAlwaysOnTop` and toggle window level while app is running
=> Toggle `window.always_on_top` while app is running

crates/vizia_core/src/context/mod.rs, crates/vizia_id/src/id_manager.rs, crates/vizia_winit/src/application.rs, crates/vizia_winit/src/window.rs
Fixes a bug where events were being handled by the window before the winit window was actually created.
=> Fix multiwindow creation

crates/vizia_core/src/views/slider.rs
if the user wants to dynamically change the range of the slider with Binding, the thumb and track will behave incorrect
> the example is modified from example/slider.rs
```rust
mod helpers;
use helpers::*;
use vizia::prelude::*;
#[derive(Debug, Lens)]
pub struct AppData {
value: f32,
max: f32,
}
pub enum AppEvent {
SetValue(f32),
SetMax(f32),
}
impl Model for AppData {
fn event(&mut self, _: &mut EventContext, event: &mut Event) {
event.map(|app_event, _| match app_event {
AppEvent::SetValue(val) => {
self.value = *val;
}
AppEvent::SetMax(max) => {
self.max = *max;
}
});
}
}
fn main() -> Result<(), ApplicationError> {
Application::new(|cx| {
AppData { value: 0.0, max: 1.0 }.build(cx);
ExamplePage::new(cx, |cx| {
HStack::new(cx, |cx| {
Binding::new(cx, AppData::max, |cx, max| {
let max = …
```
=> Clamp slider value to defined range
