core/src/views/knob.rs

This pull request adds a method to the `Knob` widget, `Knob::custom()`. 
It does the same as the `new()` methods, except instead of constructing an `ArcTrack()` it takes a closure which the user can use to build whatever thing to represent the knob that they want. 
For example, this just builds a text field showing the "knob" value, which can be dragged to change it like a knob:
```rust
Knob::custom(
cx,
default,
value,
move |cx, val| {
Label::new(cx, &format!("value: {}", val))
}
);
```

Custom knob building method

---

core/src/views/knob.rs

Just a little thing so knobs can be made smaller/larger by changing their width/height.
Made it so radius of the knob arc is the minimum of the knob's width and height, and so span is 15% of the radius, which looks pretty good to me. It was 16.667% before so maybe it should be that instead.
Not sure if this fits how you've envisioned the knobs being built but thought I'd give a pull request in case it's useful :)

Made knob arc radius based on its parent, made span percentage of radius

---

core/src/context.rs
core/src/style/mod.rs

Two changes which I found helpful while debugging my application.
- first change is self-explanitory
- second change is specifically motivated by a) being annoyed that my state would reset whenever I hit f5 (the element I was trying to style is not visible by default in my app) and b) noticing that once I added the first change, messages would appear a quadratically increasing number of times each time I hit f5 - each rebuild loads a new theme without clearing the old themes. I don't know if you also want to add logic clearing the user themes and stylesheets to the application logic that rebuilds everything, but this seemed like the easiest solution.

Print warning on unknown rules, do not rebuild application on f5

---

examples/counter.rs

This PR changes ``botton`` to ``button`` in the [counter](https://github.com/geom3trik/VIZIA/blob/main/examples/counter.rs) example.

Fix a typo in the counter example

---

core/src/context.rs
glutin/Cargo.toml
glutin/src/application.rs

Sample usage is:
```rust
cx.spawn(|cx| {
if let Some(map) = load_workflow() {
cx.emit(AppEvent::Load { map: RefCell::new(Some(map)) });
}
})
```

Add Context::spawn for spawning threads that can emit events

---

core/src/view.rs
core/src/views/stack.rs

Getting rid of these bounds enables better ergonomics and fewer clones (especially in the rebuild-always branch) at no penalty.

Remove a few static bounds

---

core/src/handle.rs
core/src/style/prop.rs
examples/controls/number_input.rs

This adds logic for classes to be removed, instead of just added. Additionally, class membership can be bound to a bool. I updated the number_input example to demonstrate this.

Add toggle_class methods to add or remove a class

---

core/src/default_theme.css
core/src/views/scrollview.rs

While trying to integrate scrollview into my app, I found that it was difficult to use because:
- It needed a Fn instead of a FnOnce
- There were inline style properties that couldn't be overridden
- The default of auto width and height leads to some strange behavior when the child is smaller than the parent
This addresses all of these.

Remove some styling and ownership restrictions from scrollview

---

core/Cargo.toml
core/src/context.rs
core/src/localization/mod.rs
core/src/resource.rs
core/src/state/binding.rs
examples/l10n.rs
examples/resources/en-US/hello.ftl
examples/resources/fr/hello.ftl

See the i10n.rs example for example usage. Long story short, you can provide a `Localized` struct anywhere a string is expected in a property setter. This struct allows you to grab a key out of the current locale's translation (translations are added with cx.add_translation(lang, flt_syntax)) and format it with a given number of args. Args are lenses, and the resulting text will be bound to the content of all the provided lenses.
```rust
Label::new(cx, Localized::new("my-key").arg("my-arg1", lens1).arg("my-arg2", lens2))
```

Basic localization with fluent

---

baseview/src/application.rs
core/src/style_system.rs
glutin/src/application.rs

- Do not measure text on elements with display: none
- Do not measure text on elements with none of min/max/size: auto
- Only measure text on relayout

Optimize text layout a bit

---

Cargo.toml
core/src/handle.rs
core/src/modifiers/actions.rs
core/src/state/binding.rs
core/src/tree/focus_iter.rs
core/src/tree/mod.rs
core/src/tree/tree_iter.rs
core/src/tree/tree_tour.rs
core/src/views/button.rs
core/src/views/stack.rs
examples/accessibility/focus_order.rs
glutin/src/application.rs

Adds ability to move focus using tab (forward) and shift + tab (backwards). Also adds action modifiers for `FocusIn` and `FocusOut` events.

Add tab focus

---

baseview/Cargo.toml
baseview/src/parent_window.rs
baseview/src/window.rs
core/Cargo.toml
core/src/context.rs
winit/Cargo.toml

OpenGL context creation is now handled by baseview instead of by raw-gl-context for the reasons outlined in https://github.com/RustAudio/baseview/pull/115. This fixes issues on a variety of desktop Linux configurations. raw-window-handle and keyboard-types have also been updated to match those used by baseview.

Update for upstream baseview changes and OpenGL context creation

---

baseview/src/application.rs
baseview/src/window.rs

This is needed when using vizia for audio plugins. On Windows and Linux the host will most likely tell the GUI what scaling factor to use. Right now there is no way to have `vizia_baseview` use the correct scaling factor. Instead of adding a new method to `vizia_baseview::Application` it would also be possible to add the scale factor to the `WindowDescription`, but I did not know if you wanted to keep `vizia_winit`'s behavior the same or not.

Allow setting a scale factor on vizia_baseview

---

core/src/style/parser.rs

Before this these selectors would be treated to target nested children. It's typical to use whitespace here, and most style guides and CSS formatters even enforce it. There's probably a neater way to implement this, but I wanted to avoid modifying the rest of the CSS parser.

Allow whitespace around > selectors

---

core/src/context.rs
core/src/events/event_handler.rs
core/src/state/binding.rs
core/src/state/store.rs
core/src/view.rs
examples/local_binding.rs

This allows descendant views to bins to data in their anscestors:
```rust
use vizia::*;
#[derive(Lens)]
pub struct CustomView {
some_data: String,
}
impl CustomView {
pub fn new<'a>(cx: &'a mut Context, txt: &str) -> Handle<'a, Self> {
Self {
some_data: txt.to_owned(),
}.build2(cx, |cx|{
Label::new(cx, CustomView::some_data)
.on_press(|cx| cx.emit(CustomEvent::ChangeData));
})
}
}
pub enum CustomEvent {
ChangeData,
}
impl View for CustomView {
fn event(&mut self, _: &mut Context, event: &mut Event) {
if let Some(custom_event) = event.message.downcast() {
match custom_event {
CustomEvent::ChangeData => {
self.some_data = "Something".to_owned();
}
}
}
}
}
fn main() {
Application::new(WindowDescription::new(), |cx|{
CustomView::new(cx, "Test");
}).run();
}
```
In the above the `Label` binds …

Add ability to bind to local view data

---

core/src/animation/animation.rs
core/src/state/mod.rs
core/src/style/prop.rs

Fixed some broken doc links I noticed when running `cargo doc`. Might be worth adding a `cargo doc` run to the CI.

Fix broken doc links

---

core/src/lib.rs
core/src/vg.rs

As suggested in #106.
Also moves vg module to lib.rs and removes unnecessary vg file.

Re-export the image crate

---

core/src/view.rs
core/src/views/button.rs
core/src/views/checkbox.rs
core/src/views/dropdown.rs
core/src/views/element.rs
core/src/views/image.rs
core/src/views/knob.rs
core/src/views/label.rs
core/src/views/list.rs
core/src/views/menu.rs
core/src/views/picker.rs
core/src/views/popup.rs
core/src/views/radio_buttons.rs
core/src/views/scrollbar.rs
core/src/views/scrollview.rs
core/src/views/slider.rs
core/src/views/stack.rs
core/src/views/table.rs
core/src/views/textbox.rs
examples/local_binding.rs
examples/local_data.rs
examples/perf_tests/rebuild.rs

I'm also open to having another method for building views with no children to avoid the `|_| {}` but I feel that `build` should be the version which allows children as it's used more often.

Remove view `build` and rename `build2` to `build`

---

core/src/context.rs
core/src/views/textbox.rs

Currently vizia will crash if it is unable to create a ClipboardProvider
using the default provider for the platform. On Linux that is X11, so if
the display is using Wayland then the application will crash on startup.
This patch falls back to `NopClipboardContext` which does nothing.
The clipboard will not work but the application will not crash.
Fully implementing Wayland support will take more work as we need need a
`RawWidnowHandle` to request a proxy, which is not available until after
the `Context` is created.

Fallback when unable to initialize the clipboard

---

.github/workflows/build.yml
Cargo.toml
core/src/views/label.rs
core/src/views/slider.rs
examples/controls/image.rs
examples/controls/widget_gallery.rs
examples/proxy.rs
examples/stylesheet.rs
winit/src/application.rs
winit/src/window.rs

Closes #61 
This also entails explicitly enumerating each example in cargo.toml instead of relying on autodiscovery for some.

Run all tests in CI: wasm, baseview, and doctests

---

core/src/style/mod.rs
core/src/view.rs

Fixes a bug where views which are added in bindings wouldn't be styled correctly until something triggered a restyle.

Restyle, relayout, and redraw when a new view is created

---

baseview/src/application.rs
baseview/src/window.rs
core/src/style/prop.rs
winit/src/application.rs

I found some references to `tuix` that were still left in the code and changed them to represent the current name `vizia` instead.

Rename `tuix` to `vizia`

---

core/src/context/mod.rs
core/src/default_layout.css
core/src/default_theme.css
core/src/style/mod.rs
core/src/style_system.rs

This makes it so that when you disable the built-in theme you don't have to re-program the layout of all the views whose layout is programmed with the default stylesheets.
Also includes some small styling fixes. (closes #101)

Move layout styles to default_layout.css

---

core/src/views/button.rs

I renamed the `Button` generic from `Label` to `V`, because it looked like it has to return a `Handle` of a `Label`, even though that is not the case. I called the generic `V` because of `View`.

Rename `Button` generic from `Label` to `V`

---

core/src/views/knob.rs
examples/more_knobs.rs

Doesn't change anything when using `Knob::new()` just makes it possible to "rotate" an `ArcTrack` when using `Knob::custom()`

knobs: make arc_start and arc_stop settable with ArcTrack::new()

---

core/src/views/checkbox.rs

I updated the doc string of the `Checkbox` and also ported some things from the [book](https://github.com/vizia/vizia-book/blob/develop/src/views/checkbox.md). I wasn't sure what the `getting` example should showcase or what it would be useful for so I didn't add it for now. If it is something useful then please let me know so I can add it.

Update `Checkbox` doc string

---

core/src/views/scrollview.rs

This would prevent events emitted from within the scroll view from reaching the outside scope.
Regression from 8ccf479dd259eb43ce9cb34d247046d888746a3d.

Prevent ScrollView from consuming every event

---

.github/workflows/build.yml
Cargo.toml
core/Cargo.toml
winit/Cargo.toml

closes #116 
This cuts a full minute off the cold compile time for my app when I only enable x11.

Make x11 and wayland optional. bump msrv to 1.60

---

core/src/window/window_description.rs

Both the `WindowSize` and the `Position` are logical and not physical. I also added some missing docs for these types.
`WindowSize` used as a logical size [here](https://github.com/vizia/vizia/blob/main/baseview/src/application.rs#L156)
`Position` used as a logical position [here](https://github.com/vizia/vizia/blob/main/winit/src/window.rs#L229)

Update `WindowSize` and `Position` docs

---

Cargo.toml
core/src/context/mod.rs
examples/key_input_propagation.rs

I fixed the key input event propagation and added an example to test this change. Once #129 lands we should definitely add a test for this instead of having it be an example.

Fix key input event propagation and add example

---

core/src/input/entry.rs
core/src/input/keymap.rs
core/src/input/mod.rs
core/src/lib.rs
examples/keymap_basic.rs
examples/keymap_change_entries.rs

I changed the way the `Keymap` works to make it more ergonomic and easy to use. The changes were made while testing the implementation inside of Meadowlark and this version makes it really easy to work with. Instead of needing a custom view to react to the `KeyDown` event the `Keymap` just does it itself and calls the appropriate callback functions. The examples also got a lot cleaner.

Add a callback to `Keymap`

---

core/src/input/entry.rs
core/src/input/keymap.rs

I removed the `Copy` requirement from the `Keymap` because it's not necessary.

Remove `Copy` trait bound from `Keymap`

---

core/src/animation/animation.rs
core/src/animation/animation_state.rs
core/src/context/mod.rs
core/src/entity.rs
core/src/events/event.rs
core/src/id/generational_id.rs
core/src/id/id_manager.rs
core/src/id/mod.rs
core/src/input/mouse.rs
core/src/style/display.rs
core/src/style/mod.rs
core/src/style/parser.rs
core/src/style/rule.rs
core/src/tree/tree_ext.rs
core/src/tree/tree_iter.rs
core/src/views/element.rs
core/src/views/textbox.rs

- Combined the index and generation constants.
- Made a macro for the duplicated implementation in `Entity`, `Rule` and `Animation`.
- Added `PartialEq` trait bound for `GenerationalId`.
- Added `null` function to `GenerationalId`.
- Added docs.
- Fixed some broken doc links.

Reduce `GenerationalId` code duplication

---

core/resources/themes/default_theme.css
core/src/hover_system.rs
core/src/style_system.rs
core/src/views/checkbox.rs
examples/views/checkbox.rs

- Update checkbox styling.
- Update the checkbox example to show off new styling.
- Fix a bug where multiple pseudoclass selectors weren't matching correctly. For example:
This rule...
```css
checkbox:checked:hover {
background-color: red;
}
```
should have a higher specificity than this rule...
```css
checkbox:hover {
background-color: green;
}
```
but previously the former rule wasn't matching at all on the element, causing the latter rule to be selected in error. This is now fixed.

Update checkbox style and example

---

core/src/resource.rs

I noticed that the l10n example wasn't working for me then realised that my system locale is en-GB so it's failing to find a suitable translation bundle. This fixes it by defaulting to the resource manager language determined by the `renegotiate_language` function.

Default to first available fluent bundle

---

core/src/context/mod.rs
core/src/handle.rs
core/src/style/mod.rs
core/src/tree/focus_iter.rs
core/src/tree/mod.rs
core/src/views/button.rs
core/src/views/label.rs

- Focus style updates displays immediately
- The `focus_order` example always keeps your focus on the buttons
- Add `KEYBOARD_NAVIGATABLE` ability to allow for focusable elements that are not in the tab order (the equivalent of `tabindex="-1"` in html)
- Buttons get focused on click (this triggers the focus pseudo class which equivalent behaviour to html - html also has the `:focus-visible` pseudo class to only show the style when using keyboard navigation which we may also want)

Focus improvements

---

core/src/context/mod.rs

This fixes an incredibly annoying and incredibly difficult to pin down bug I was lucky enough to reproduce in arborio this morning. Basically, if you have a view which is only ever used in the context of a parent view and whose builder assumes the conditions necessary to build the parent are satisfied, and the parent gets removed because its preconditions are invalidated AND the child gets marked for rebuild in the same cycle, the child may panic while rebuilding because it should not be being rebuilt!
The fix is to a) rebuild observers in tree order and b) keep track of which entities have been removed, and if so, skip them during the observer update process.

Do not rebuild entities if their parent has been rebuilt

---

core/resources/themes/default_theme.css
core/src/context/backend.rs
core/src/context/event.rs
core/src/context/mod.rs
core/src/entity.rs
core/src/handle.rs
core/src/lib.rs
core/src/modifiers/actions.rs
core/src/style/mod.rs
core/src/style/parser.rs
core/src/style/selector.rs
core/src/tree/focus_iter.rs
core/src/views/button.rs
core/src/views/checkbox.rs
core/src/views/label.rs
core/src/views/menu.rs
core/src/views/radio_buttons.rs
core/src/views/stack.rs
core/src/views/textbox.rs
core/src/window/window_event.rs
examples/accessibility/focus_order.rs
examples/views/checkbox.rs
examples/views/label.rs
examples/views/radiobutton.rs

- `:focus-visible` and `focus-within` added
- Add focus styles to the default stylesheet
- TriggerDown and TriggerUp event which is called on left mouse down and on enter/space.
- Labels can describe other elements similar to the html for attribute

Trigger buttons with keyboard navigation

---

crates/vizia_core/resources/themes/default_theme.css
crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/views/textbox.rs

Fix bugs with textbox introduced by #187.
- The textbox can remain focused but not in an edit state. The `:check` pseudoselector is used to show the cursor and border when the textbox is in an edit state.
- The `TriggerDown` event was not being sent to the captured entity which meant that the textbox could not be set to non edit by clicking away from it.
- The `Enter` key used for the Trigger event was not working correctly with the submit event of the textbox which is also triggered with the `Enter` key so I removed the `Enter` key causing a Trigger event.

Fix bugs with textbox introduced by #187

---

src/lib.rs

This is an experiment to see if adding the demo to the documentation using an embedded iframe will work when the docs are published externally (and eventually to docs.rs)

Add demo to docs

---

crates/vizia_baseview/src/application.rs
crates/vizia_baseview/src/window.rs
crates/vizia_core/src/context/backend.rs
crates/vizia_winit/src/application.rs

These are necessary for arborio to function performantly :) I was previously accessing text_context directly off of Context, but that was made private in the BackendContext cleanup.

Add APIs to adjust some femtovg cache sizes

---

crates/vizia_core/src/cache.rs
crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/state/binding.rs
crates/vizia_core/src/state/lens.rs
crates/vizia_core/src/views/knob.rs
crates/vizia_core/src/views/table.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_derive/src/lens.rs

- The tree structure is more clear (using ascii art from the `tree` command)
- Bindings are labelled with what they are binding to
- All views in core are labelled

Improvements to debug tree (i key)

---

crates/vizia_baseview/src/window.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_winit/src/application.rs

The logic to skip index 1 of themes if ignoring the default theme was a hack, this does it properly (?). As a consequence, this lets us remove the theme includes from the backends.

Fix ignore_default_theme + add_theme

---

crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/context/event.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/text/edit.rs
crates/vizia_core/src/text/layout.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_window/src/window_event.rs

- Double click to select word and triple click to select paragraph
- When editing is false, you can now properly select a range by dragging. If you don't drag, then it will select all as before.
- When you click outside a textbox, it didn't send a triggerdown event, only a mousedown.

Textbox improvements

---

crates/vizia_core/src/views/scrollview.rs

For a scrollview which grows/shrinks with the parent (e.g. the window), scrolling to the end and then resizing the parent so that the scroll is no longer required, then resizing the parent again so that the scroll *is* required, causes the scoll container to 'stick' to the bottom of the scrollview. This is because the scroll_y (or scroll_x) value is 1.0 when scrolled to the end but resizing the child/parent until the scoll is no longer required should reset this back to 0.0, which is what this PR implements.

Reset scroll position when parent and child size are equal

---

crates/vizia_core/src/systems/style.rs

The disabled state was being ignored when performing the optimization which skips style matching when siblings have the same selector. This resulted in disabled siblings being ignored. Fixed by applying the disabled state to the selector.

Fix for disabled state style matching

---

crates/vizia_core/src/state/res.rs

Implements `Res` trait for `Option<T>` as long as `T` also implements `Res`. This allows, for example, for `Some((u32, u32))` to be passed to window modifiers such as `min_inner_size`.

impl res for option

---

crates/vizia_core/src/context/event.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/context/proxy.rs
crates/vizia_core/src/events/event.rs
crates/vizia_core/src/events/mod.rs
crates/vizia_core/src/lib.rs
crates/vizia_core/src/state/mod.rs
crates/vizia_core/src/state/ray.rs
crates/vizia_derive/src/attr.rs
crates/vizia_derive/src/lens.rs
crates/vizia_derive/src/lib.rs
crates/vizia_derive/src/model.rs
crates/vizia_derive/src/ray.rs
examples/views/dropdown.rs
examples/views/knob.rs
examples/views/radiobutton.rs
examples/views/textbox.rs

A Ray is a new concept which is just a value pending application to a struct. Deriving Ray on `MyStruct` produces a `MyStructRay` enum, which has a variant for each field of the struct. You can call Ray::apply or Ray::swap to apply a ray to the relevant struct.
I've been programming with a prototype of this paradigm in arborio for a few weeks, and the thing I found is that sometimes you want the strike operation to actually be a swap between the struct and the enum - this allows you to inspect the result of the operation post-facto and also gets you an inverse of the event for free - perfect for implementing undo-redo. In order to facilitate this, I had to put RefCells in all of my events, so to smooth that over I introduced Event::take. This required getting rid of the Message type …

Add Rays and Event::take

---

crates/vizia_baseview/src/application.rs
crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/events/event.rs
crates/vizia_core/src/events/event_manager.rs
crates/vizia_core/src/style/color.rs
crates/vizia_core/src/style/display.rs
crates/vizia_core/src/style/mod.rs
crates/vizia_core/src/style/property.rs
crates/vizia_core/src/style/shadow.rs
crates/vizia_core/src/style/style_rule.rs
crates/vizia_core/src/systems/style.rs
crates/vizia_core/src/views/menu.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_core/src/window/mod.rs
crates/vizia_window/src/cursor.rs
crates/vizia_winit/src/application.rs

As discussed on discord. This has the weird side effect that WindowEvents get emitted without _any_ targeting information, and then the event manager targets them as it processes them, but I think this is desired behavior.

Make window events not read or write state until it is their turn in line

---

crates/vizia_baseview/Cargo.toml
crates/vizia_baseview/src/application.rs

Using the changes from https://github.com/RustAudio/baseview/pull/117.
Until baseview implements proper keyboard focus handling this helps when dragging a knob or slider outside of the window. Otherwise the modifier state may get stuck on an incorrect value.

Set modifiers on baseview mouse events

---

crates/vizia_core/src/cache.rs
crates/vizia_core/src/systems/hover.rs
crates/vizia_core/src/systems/style.rs
crates/vizia_core/src/views/button.rs

This means that children of a container which is marked non-hoverable will also be non-hoverable. Allows for the cursor icon to be set for a button, even when it contains multiple descendent views, such as a label + icon.

Propagate hoverability state

---

crates/vizia_core/src/handle.rs
crates/vizia_core/src/lib.rs
crates/vizia_core/src/modifiers/abilities.rs
crates/vizia_core/src/modifiers/layout.rs
crates/vizia_core/src/modifiers/mod.rs
crates/vizia_core/src/modifiers/style.rs
crates/vizia_core/src/modifiers/text.rs
crates/vizia_core/src/state/data.rs
crates/vizia_core/src/state/res.rs
crates/vizia_core/src/style/mod.rs
crates/vizia_core/src/tree/focus_iter.rs
crates/vizia_core/src/views/button.rs
crates/vizia_core/src/views/checkbox.rs
crates/vizia_core/src/views/knob.rs
crates/vizia_core/src/views/menu.rs
crates/vizia_core/src/views/radio_buttons.rs
crates/vizia_core/src/views/slider.rs
crates/vizia_core/src/views/textbox.rs

This is part of an ongoing effort to improve the documentation of the vizia crate. The modifiers which apply to `Handle` have now been split up accross multiple traits to improve organisation and the generated docs.
This PR also renames the ability `KEYBOARD_NAVIGATABLE` to `NAVIGABLE`.

Split modifiers into separate traits

---

crates/vizia_core/src/context/event.rs
crates/vizia_core/src/modifiers/actions.rs
crates/vizia_core/src/views/scrollview.rs
crates/vizia_core/src/views/slider.rs
examples/action_modifier.rs

While working with action modifiers, e.g. `on_press(|cx| ...)` I realised it would be very useful to be able to mutate the actual view data. To do this the view type needs to be known so that the view can be retrieved from the context. This PR adds an `EventHandle`, which is similar to `Handle` but wraps an `EventContext`. This is then used by action modifiers to provide a way to mutate the view data in response to an event. See `action_modifier` example to see how this works.

Add `EventHandle` so that action modifiers can mutate view data

---

crates/vizia_core/src/view.rs

The diff looks a bit wild, but I just moved the content of the `draw` function of the `View` trait into a separate function called `draw_view`. This reduces the binary size quite a bit.
Old: 13752 kb
New: 13484 kb
Old: 13936 kb
New: 13608 kb
Old: 8784 kb
New: 8696 kb
Old: 8972 kb
New: 8832 kb

Optimize draw call in view trait

---

crates/vizia_core/src/views/textbox.rs
examples/views/textbox.rs

Closes #92, kind of, it doesn't actually implement the parameter described in that issue but I'm not convinced such a parameter needs to exist. I am pretty sure we have selection behavior parity with most other gui toolkits.

Textbox: Do not select all on start, do not scroll on end

---

Cargo.toml
crates/vizia_core/src/events/event_manager.rs
crates/vizia_window/src/window_event.rs
crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs
examples/save_dialog.rs

Fixes #207.
Also added example for a save dialog which uses a model to intercept the `WidowClose` event and conditionally consume it before it can be handled by the window.
As a result of this, event handling has been changed so that for a particular entity events are handled by attached models first and then by the associated view. Events consumed by models will not propagate to the view. Hopefully this doesn't have any unforeseen consequences.

Use `WindowClose` event to close the window

---

crates/vizia_baseview/src/application.rs
crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/context/event.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/events/event_manager.rs
crates/vizia_core/src/modifiers/style.rs
crates/vizia_core/src/modifiers/text.rs
crates/vizia_core/src/storage/animatable_set.rs
crates/vizia_core/src/style/mod.rs
crates/vizia_core/src/systems/animation.rs
crates/vizia_core/src/systems/layout.rs
crates/vizia_core/src/systems/mod.rs
crates/vizia_core/src/systems/style.rs
crates/vizia_core/src/systems/text_constraints.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_winit/src/application.rs
examples/7GUIs/crud.rs
examples/lists/editable_list.rs
examples/lists/multiselectable_list.rs
examples/lists/selectable_list.rs
examples/lists/static_list.rs
examples/views/radiobutton.rs

- Prevents animation system from triggering relayout all the time
- Splits the text constraints system from layout so that only text which has changed causes content-size computation, and then only content size which is different to bounds results in relayout.
- Update some examples to use property bindings instead of the `Binding` view to prevent unnecessary relayout.

Some small performance improvements

---

Cargo.toml
crates/vizia_baseview/Cargo.toml
crates/vizia_baseview/src/application.rs
crates/vizia_baseview/src/window.rs
crates/vizia_core/Cargo.toml
crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/context/draw.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/systems/draw.rs
crates/vizia_core/src/text/cosmic.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_winit/Cargo.toml
crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs

As far as I can tell these are the minimal set of changes required for [nih-plug](https://github.com/robbert-vdh/nih-plug) to depend on vizia main rather than a fork of vizia, which will make it easier for nih-plug to adopt changes to vizia.
- Added feature to allow disabling the default fonts from bein embedded into the binary.
- Added `set_text_config()` method on `Application` to allow configuring the hinting and subpixel rendering of text using a new `TextConfig` type.
- Updated femtovg to v0.4.0

Changes to allow nih-plug to depend on vizia main

---

crates/vizia_winit/src/window.rs

Don't know if this is just a windows thing but apparenty minimizing the window sends a resize event with 0 size. Which is just weird... Anyway this fixes a panic caused by the `try_into` conversion from u32 to NonZeroU32.

Fix for panic when minimizing window

---

crates/vizia_core/src/systems/style.rs

Ok thats a small line of code but i think that should do it. I didn't found any tests so on your risk 😅
Also: from lines like https://github.com/vizia/vizia/blob/new-style-system/crates/vizia_style/selectors/matching.rs#L993 i think selectors like `:first-child` and `:last-child` should be also done but ill check on this again.

Implement `is_empty`

---

Cargo.toml
crates/vizia_core/src/environment.rs
crates/vizia_core/src/lib.rs
crates/vizia_core/src/state/lens.rs
crates/vizia_core/src/state/res.rs
crates/vizia_core/src/views/scrollview.rs
crates/vizia_derive/src/lens.rs
examples/binding/boolean.rs

This PR adds three new lenses:
- The first is a tuple lens which can be used like so in a binding view:
```rust
// Rebuilds if either target data of lens1 or lens2 changes.
Binding::new(cx, (lens1, lens2), |cx, (l1, l2)|{
});
```
Or like so with a `map`:
```rust
(lens1, lens2).map(|(l1, l2)|{...});
```
This currently only works if the `Source` of lens1 is the same as the `Source` of lens2. 
This gets us one small step closer to 'derived data', which is data we can bind to that doesn't exist in a model(s) but is derived from data which does. `Map` allows us to derive data from a single lens, and now the tuple lens, combined with `map`, lets us derive data from multiple lenses of the same model (tuple lenses can be combined with other tuple lenses). Ideally in the future we would like to …

Add tuple lens and boolean or & and lenses

---

crates/vizia_core/src/style/color.rs

Previously, when parsing a short color code with alpha, it read byte 0 into the alpha, which is actually the red channel. This fixes that, as well as refactors the surrounding code for clarity and adds a test.

Fix parsing short color codes with alpha

---

Cargo.toml

This meant that winit was always compiled in, even when using baseview. I noticed that my NIH-plug builds suddenly started requiring a bunch of wayland libs to be installed.

Don't unconditionally require winit for the clipboard feature

---

crates/vizia_core/src/state/res.rs

This commit:
https://github.com/vizia/vizia/commit/4a638441a98af74c4719400897077ae479eda8ae 
broke code using the `translate( (f32, f32))` modifier, adding a Res impl like this seems to fix it

add Res impl for (f32, f32)

---

README.md

This PR fixes the README links because Markdown syntax does not work in HTML tags.

Fix: README Summary/Details

---

crates/vizia_core/src/fonts.rs

Small addition to the `ICON_PLAYER` icons, now supporting FILLED icons as well.
In addition there is now a ` ICON_REPEAT_OFF` icon as well.

filled player icons, and repeat off

---

crates/vizia_core/src/util/mod.rs

seems like at some point the `from_str` function renamed to `from_string` but the method name didn't changed in the `include_style` macro, this will fix it

Change `from_str` to `from_string` to fix stylesheet loading

---

Cargo.toml
crates/vizia_core/Cargo.toml
crates/vizia_core/src/lib.rs
crates/vizia_core/src/resource.rs
crates/vizia_winit/Cargo.toml
examples/animation.rs
examples/keyframes.rs
examples/proxy.rs
examples/style/background_image.rs
examples/style/background_size.rs
examples/style/filter.rs

Removed the `reqwest` dependency for now because it pulls in nearly 80 other crates. It's still a dev dependency to demo loading images from the web but I'd like to move that to a dedicated example package so that simpler examples don't need to pull in all these crates.

Cleanup and update dependencies

---

crates/vizia_core/src/views/button.rs

`WindowEvent::PressDown` event in button were previously capture mouse input even if user didn't used mouse to press the button, this would lead to a bug that mouse would get captured without ever get released.

Fixed the problem of capturing mouse even if user didn't used mouse

---

crates/vizia_core/src/views/scrollview.rs

I tried to reverse engineer some fields in Scrollview as preparation work for #74.
@geom3trik would you check over this and say if this is correct? Thanks :D
Other naming idea:
* `content_(width/height)` and `(width/height)`

Documenting and renaming fields in Scrollview

---

crates/vizia_winit/Cargo.toml

Disabling vizia's `wayland` feature wouldn't completely disable winit's wayland backend. This was caused by this feature chain: `glutin-winit/default` -> `glutin-winit/wayland` -> `winit/wayland`.

Fix winit wayland features always getting enabled

---

crates/vizia_core/src/window/window_modifiers.rs
crates/vizia_winit/src/application.rs

I encountered this minor annoyance when trying to give my application an icon. As far as I can tell the "canonical" way to apply application icons in vizia is to use `load_from_memory` and pass the data into `Application::icon`. Unfortunately the argument order for `Application::icon` takes the bytes first, which requires consuming the icon via `.into_bytes()`, after which you can longer access `.weight()` and `.height()` which are needed for the second and third arguments. 
This PR simply changes the argument order so you can pass all arguments in the same line without binding temporary variables. I also went ahead and filled in the example in the method documentation.
```rs
let icon = vizia::image::load_from_memory(include_bytes!("../icon.png"))
.expect("Failed to load icon"); …
```

Improve `Application::icon` method argument order.

---

crates/vizia_core/src/context/mod.rs

Fixes an issue where the accessibility tree wasn't being updated correctly when the children of a node were removed. This is because the child nodes are updated by triggering an accessibility update (`TreeUpdate`) on the parent, passing in the updated list of children. This PR fixes the issue by flagging the parent for an accessibility update when children are removed.

Trigger update on parent access node when children are removed

---

crates/vizia_core/src/systems/accessibility.rs
crates/vizia_core/src/view.rs

Fix for accesskit panic when node has layout children as well as generated child nodes

Fix accesskit panic

---

crates/vizia_core/src/views/textbox.rs

The `TextEvent::InsertText` is called when the textbox is updated externally (via binding), which was triggering the `on_edit` callback. This was then calling the `ComboBoxEvent::SetFilterText` event, which opens the popup if closed. This PR adds a check to see if the textbox is editable before calling `on_edit`.

Fix for combobox opening on init

---

crates/vizia_core/resources/themes/default_layout.css
crates/vizia_core/src/views/dropdown.rs

1. Move styling to `default_layout.css` rather than hard-coding it in rust. This is needed to enable user customization.
2. Add `checked` modifier to the dropdown title. This allows it to be styled differently when opened versus closed.
It was suggested on discord that refactoring the `Dropdown` itself to hold the `is_open` state may be a better solution to `2`, but that is a larger change and I'm not familiar enough with the internals yet to implement it.

Minor improvements to the `Dropdown` view.

---

crates/vizia_core/src/tree/focus_iter.rs
crates/vizia_storage/src/tree/iter/focus_iter.rs
crates/vizia_storage/src/tree/iter/mod.rs

Fixes a bug where the descendants  of non-displayed views could still be navigated to with tab/shift-tab.

Skip non-displayed views when iterating focus

---

crates/vizia_winit/Cargo.toml
crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs

See: https://github.com/rust-windowing/winit/issues/1290
Fix explained here: https://stackoverflow.com/a/74019785
Cloak attribute documentation: https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute
TL;DR: Set the `Cloak` window attribute on creation, hiding the window, then unset it once the first draw is complete. `Cloak` differs from `Visible` in that the window will still be composited, allowing said draw to actually work.

Fix the "blank window flash" problem on windows.

---

Cargo.toml
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/environment.rs
crates/vizia_core/src/events/event.rs
crates/vizia_core/src/events/timer.rs
crates/vizia_core/src/lib.rs
crates/vizia_core/src/window/window_event.rs
crates/vizia_winit/src/application.rs
examples/follow_system_theme.rs
examples/helpers/mod.rs
examples/views/helpers/mod.rs

This event will get emitted when current system theme changed.
I also added a new example to showcase this new event.
currently this new event is only supported with winit backend (Im not sure if baseview support such a thing).

Added `WindowEvent::ThemeChanged` event

---

crates/vizia_core/src/animation/animation_state.rs
crates/vizia_core/src/binding/binding_view.rs
crates/vizia_core/src/binding/store.rs
crates/vizia_core/src/context/event.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/context/resource.rs
crates/vizia_core/src/resource.rs
crates/vizia_core/src/style/mod.rs
crates/vizia_core/src/systems/binding.rs
crates/vizia_core/src/systems/image.rs

Previously (208ec91dee8f51bca76fde6e335ccbf9cc1d4f33) replaced `HashMap` occurrences, this commit extends that to cover `HashSet` as well.

Replace `std::collections::HashSet` with `hashbrown::HashSet`

---

crates/vizia_core/src/views/virtual_list.rs

Follow up and fixes to #451
1. Fixes a panic that was caused by the `num_items` field not being initialized in the `new` method.
2. Restores `.scroll_to_cursor(true)` that accidentally got left out. Hopefully this changes to shift+click instead when the "standardized" scroll behavior is implemented.
3. Implements the additional performance improvements theorized in the previous PR comments. Now the `VirtualList` does not store any additional list of items all, and only holds a `visible_range: Range<usize>`. In addition to the memory savings, all related methods are now constant-time and non-allocating. The `on_change` callback is now free as well, though maybe it's less necessary as we can bind to `VirtualList::visible_range` directly.
4. Added tests so further tweaks are less likely to …

More VirtualList performance improvements and fixes.

---

crates/vizia_core/Cargo.toml
crates/vizia_window/Cargo.toml
crates/vizia_winit/Cargo.toml

The default feature "async-io" conflicts with applications that use the Tokio runtime.
Example: Adding `rfd` as a dependency with features "tokio" and "xdg-portal" causes a panic on startup.

accesskit: Disable default features

---

README.md

I have noticed that many dependencies are outdated. Upgrading them requires migrating existing code. Relying on unmaintained versions is not an option.
This PR adds a [deps.rs](https://deps.rs/repo/github/vizia/vizia) badge to the README to show the current status.

Add deps.rs badge to README

---

crates/vizia_core/src/storage/animatable_set.rs
crates/vizia_core/src/storage/style_set.rs
crates/vizia_id/src/id_manager.rs
crates/vizia_storage/src/tree/iter/layout_child_iter.rs
crates/vizia_style/selectors/bloom.rs
crates/vizia_style/selectors/parser.rs
crates/vizia_style/src/matching.rs
crates/vizia_style/src/selector.rs
crates/vizia_winit/src/application.rs
examples/7GUIs/flight_booker.rs
examples/lens_map.rs
examples/save_dialog.rs
examples/style/filter.rs
examples/views/hstack.rs
examples/views/label.rs
examples/views/menu.rs
examples/views/menubar.rs
examples/views/spinbox.rs
examples/views/vstack.rs
examples/views/zstack.rs
examples/widget_gallery/src/views/menu.rs
examples/widget_gallery/src/views/menu_bar.rs
examples/widget_gallery/src/views/toggle_button.rs

Removed temporary fix in windows because its already fixed in winit and also fixed all clippy warnings

Removed the `MouseEnter` and `MouseLeave` temporary fix and fixed all clippy warnings

---

Cargo.toml
crates/vizia_core/resources/themes/dark_theme.css
crates/vizia_core/resources/themes/default_layout.css
crates/vizia_core/resources/themes/light_theme.css
crates/vizia_core/src/views/mod.rs
crates/vizia_core/src/views/xypad.rs
examples/views/xypad.rs

* Adds XY pad view
* Supports disabling
* Supports light/dark themes
* Adds an example for the new view

Feat: Adds xypad and an example for it

---

crates/vizia_core/Cargo.toml

Femtovg uses image 0.25.0, yielding the following error when building our vizia application: 
``error[E0277]: the trait bound `ImageSource<'_>: std::convert::From<&image::DynamicImage>` is not satisfied
--> ~/.cargo/git/checkouts/vizia-a7ac1d316660c1f9/5b548c3/crates/vizia_core/src/resource.rs:32:35
|
32 |                     .create_image(femtovg::ImageSource::try_from(image_ref).unwrap(), *flags)
|                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<&image::DynamicImage>` is not implemented for `ImageSource<'_>`
|
= help: the following other types implement trait `std::convert::From<T>`:
<ImageSource<'a> as std::convert::From<Img<&'a [RGB<u8>]>>>
<ImageSource<'a> as std::convert::From<Img<&'a [femtovg::rgb::RGBA<u8>]>>> …

Bump image to 0.25.0

---

crates/vizia_core/src/animation/animation_state.rs
crates/vizia_core/src/binding/res.rs
crates/vizia_core/src/layout/bounds.rs
crates/vizia_core/src/lib.rs
crates/vizia_core/src/localization/mod.rs
crates/vizia_core/src/systems/style.rs
crates/vizia_core/src/views/combobox.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_id/src/id_manager.rs
crates/vizia_style/src/values/color.rs
crates/vizia_winit/src/lib.rs
crates/vizia_winit/src/window.rs

Fixes an issue where some lenses which couldn't be bound to also couldn't implement `Res` for just getting the value.

Split Res trait into ResGet

---

crates/vizia_winit/Cargo.toml
crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs

Fixes the "white flash" startup bug on Windows. Previously #386 had solved it, but it came back again after the recent winit update.
The new winit update also has an issue where windows have incorrect position/size for one frame after creation. This update addresses that problem as well.
Also switches from the unofficial `winapi` crate to the official `windows` crate. Since winit has done the [same](https://github.com/rust-windowing/winit/blob/v0.30.x/Cargo.toml#L211) already. Our version numbers should be kept in sync when possible, but if rust-windowing/winit#3576 gets accepted we could remove this code and dependency entirely.

Fix the "white flash" and other window creation issues on Windows.

---

crates/vizia_core/src/binding/binding_view.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/environment.rs
crates/vizia_core/src/lib.rs
crates/vizia_derive/src/lens.rs
src/lib.rs

> Don't set default font to Fire Sans
I assume this was left over from before removing `embedded_fonts`.
> Simplify more cases of .with(|f| f.borrow(...))
The `with_borrow_mut` function was added in rust 1.73. I also refactored the surrounding code to avoid allocating temporary `Vec` structs.
> Use absolute paths in derive macro. Fix rust-analyzer syntax warnings.
Allows `#[derive(Lens)]` to work without also having to also import `LensValue`, `Wrapper`, and other non-obvious dependencies. This also avoids name clashes that might have happened if the user had their own `Wrapper` (or other) types. I inserted some spacing around `#var` usages as without it rust-analyzer currently gives syntax errors.

Skia minor fixes

---

Cargo.toml
crates/vizia_baseview/Cargo.toml
crates/vizia_baseview/src/proxy.rs
crates/vizia_baseview/src/window.rs
crates/vizia_core/Cargo.toml
crates/vizia_derive/Cargo.toml
crates/vizia_id/Cargo.toml
crates/vizia_input/Cargo.toml
crates/vizia_storage/Cargo.toml
crates/vizia_style/Cargo.toml
crates/vizia_window/Cargo.toml
crates/vizia_winit/Cargo.toml
examples/designer/Cargo.toml
examples/text_layout.rs
examples/widget_gallery/Cargo.toml

Previously we were hardcoding `vizia` path in examples `widget_gallery` and `designer` and that caused cargo to fail compiling the project if we had renamed the vizia directory to something other then `vizia`... this PR aim to fix this problem.
we now have the `vizia` crate available as a workspace dependency, so we can use it directly in mentioned examples.
- put some common package information in workspace and used them in all crates when possible.
- put vizia itself inside workspace dependencies so we can use it internally, without hardcoding vizia path.
- commented out 'reqwest' as its unused right now.

Updated `Cargo.toml`

---

crates/vizia_winit/src/window.rs

Fixes window size not being round-tripped correctly when being saved/loaded via `cx.window_size()` then `Application::inner_size()`. I believe it was previously working only on systems without DPI scaling; my windows desktop behaved as expected but macos laptop did not.
It seems to be the cause was that the `window_size()` method was retrieving the size from `cx.cache.get_bounds(parent_window)` which uses physical units rather than logical.

Fix incorrect type used in `WindowEvent::SetSize` and related events.

---

crates/vizia_core/src/view/handle.rs

adding this, to a popup window, causes a panic.
```rust
....
.title(Localized::new("popup-new-project-title"))
```
stack trace from my app
```
thread 'main' panicked at D:\Users\Hydra\.cargo\git\checkouts\vizia-cb149d0347f9ee86\ced07cf\crates\vizia_core\src\localization\mod.rs:247:34:
Failed to get context
...
5: vizia_core::localization::impl$5::get<vizia_core::view::handle::Handle<vizia_winit::window::Window> >
at D:\Users\Hydra\.cargo\git\checkouts\vizia-cb149d0347f9ee86\ced07cf\crates\vizia_core\src\localization\mod.rs:247
```
after looking at the code, it's using the default implementation of `DataContext::as_context` on the `vizia_core::view::handle::Handle<vizia_winit::window::Window>` type (as per stacktrace).
after looking a bit more I found this in the impl of …

Fix ability to localize titles of popup windows.

---

crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs
crates/vizia_winit/src/window_modifiers.rs

Makes it possibile to set the window visibility via Lens:
```rust
#[derive(Lens)]
struct AppData {
pub visible: bool,
}
fn main() {
let _ = Application::new(|cx| {
AppData { visible: true }.build(cx);
})
.visible(AppData::visible)
.run();
}
```
Issue: When visible(false) is used, the window still pops up and hides then. This should be hidden and should not popup.

Fix window visibility modifier

---

crates/vizia_core/Cargo.toml

Build time for the `stylesheet` example improved slightly from ~24s to ~22s on my M1 pro machine. Dependency count is reduced from 264 to 250.

Upgrade comrak to 0.33

---

crates/vizia_core/src/context/backend.rs
crates/vizia_core/src/layout/node.rs
crates/vizia_core/src/views/scrollview.rs
crates/vizia_winit/src/application.rs

Sets initial scale factor for windows and updates text when scale factor changes.
**Known Issues**
Scale factor is currently set per application rather than per window as it should be. Fixing this will require fixing layout so that it only runs per window rather than on the whole application. This itself will require a new iterator that skips sub-windows. This will be done in a follow-up PR.

Fix init scaling + scaling for scroll

---

examples/7GUIs/circle_drawer.rs

Reverted to using popup widget instead of dialog button, fixed menu not sending on_press event, and displaying coordinates in the popup for the circle radius size.

Fixes for circle demo

---

crates/vizia_core/src/context/event.rs
crates/vizia_core/src/context/mod.rs
crates/vizia_core/src/events/event_manager.rs
crates/vizia_core/src/text/mod.rs
crates/vizia_core/src/text/preedit_backup.rs
crates/vizia_core/src/views/textbox.rs
crates/vizia_core/src/window/window_event.rs
crates/vizia_input/src/ime.rs
crates/vizia_input/src/lib.rs
crates/vizia_winit/src/application.rs
crates/vizia_winit/src/window.rs

Tested on Windows 10 and 11 with Microsoft IME (Chinese and Japanese).  
There might be some issues with the Japanese IME, but I’m not familiar with how it works, so I’m not sure if it functions correctly.  
Currently, the IME window does not follow the cursor movement—it is only positioned at the textbox. I will address this issue in a separate PR.

Add basic support for IME

---

crates/vizia_core/src/context/mod.rs

Clipboard wasn't working on my Windows machine. I did not test it on others, but I think this will fix the problem.
We already forward the `x11` and `wayland` feature flags to `copypasta` in our [Cargo.toml](https://github.com/vizia/vizia/blob/main/crates/vizia_core/Cargo.toml#L11), so (I think) the appropriate implementation should be automatically selected for us by the `copypasta` crate itself. See their [feature handling code](https://github.com/alacritty/copypasta/blob/master/src/lib.rs#L59) for reference.

Fix clipboard feature not working when `x11` feature is disabled.

---

Cargo.toml
crates/vizia_winit/Cargo.toml

`wayland` is a `cargo` feature of `vizia`, but the `wayland` crate is always a dependency of `vizia` (when the `winit` feature is specified). The reason is that `wayland` is a default dependency of the crates `winit`, `glutin` and `glutin-winit`. This pull request addresses this by no longer using default features for `winit`, `glutin` and `glutin-winit`.

Do not use default features for winit

---

crates/vizia_core/resources/themes/dark_theme.css
crates/vizia_core/resources/themes/default_layout.css
crates/vizia_core/resources/themes/light_theme.css
crates/vizia_core/src/binding/res.rs
crates/vizia_core/src/context/event.rs
crates/vizia_core/src/views/slider.rs
examples/views/slider.rs

- Removes the need for `GeoChanged` events by adding methods to `EventContext` to retrieve entity ids by element name and class id.
- Add a dedicated track element so the slider can encompass both the track and the thumb making it less fiddly to manipulate.
- Makes all slider modifiers bindable and removes internal slider events.

Improve Slider view

---

crates/vizia_winit/Cargo.toml
crates/vizia_winit/src/application.rs

Closes #558
In order to support tilling window managers, wayland doesn't let you set or get the position of a window. In order to create popup windows with a particular anchor, the [xdg_popup](https://wayland.app/protocols/xdg-shell#xdg_popup) is provided. However this is unfortunately not supported in winit https://github.com/rust-windowing/winit/issues/403.
Since winit hasn't added support for popup windows for 7 years, it is probably best to just log a warning instead of crashing.

Warn instead of crash for positioning a window on wayland

---

crates/vizia_baseview/src/application.rs

On my macOS system HiDPI scaling isn't applied. I'm using vizia in vizia-plug.
There's this note in "crates/vizia_baseview/src":
```
// NOTE: This is not correct, but we should get a `Resized` event to correct this
//       immediately after the window is created
WindowScalePolicy::SystemScaleFactor => (true, 1.25),
```
But the `Resized` event never corrects this initial 1.25 value. 
This PR fixes this by setting the new system scale factor when a `Resized` is received. 
Something similar was commented out by mistake I think.
Related to this Discord question: https://discord.com/channels/791142189005537332/1402216886623535226

Apply window_scale factor when resized
